basic_app/urls.py
from django.conf.urls import url
from django.http.request import MediaType
from basic_app import views

app_name = 'nasrin'

urlpatterns = [
    url(r'^education/$',views.education,name='education'),
    url(r'^experience/$',views.experience,name='experience'),
    url(r'media/$',views.media,name='media'),
]

nasrin_web/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.urls import path
from django.urls.conf import include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('nasrin/',include('basic_app.urls')),
]

basic_app/models.py
from django.db import models

# Create your models here.

basic_app/views.py
from django.http import request
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'basic_app/index.html')

def education(request):
    return render(request,'basic_app/education.html')


def experience(request):
    return render(request,'basic_app/experience.html')

def media(request):
    return render(request,'basic_app/media.html')

templates/basic_app/base.html
<!DOCTYPE HTML>
<html>
    <head>
        <meta charset="utf-8">
        <title></title>
        <link rel="stylesheet" href="https://static-exp1.licdn.com/sc/h/2hco4zdbr24744fjnzwvpdeos">
        <link rel="stylesheet" href="https://static-exp1.licdn.com/sc/h/al2o9zrvru7aqj8e1x2rzsrca">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
            <script>
              function getDfd() {let yFn,nFn;const p=new Promise(function(y, n){yFn=y;nFn=n;});p.resolve=yFn;p.reject=nFn;return p;}
              window.lazyloader = getDfd();
              window.tracking = getDfd();
              window.impressionTracking = getDfd();
              window.ingraphTracking = getDfd();
              window.appDetection = getDfd();
              window.pemTracking = getDfd();
            </script>
    </head>
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
                       
            <div class="container">
                <ul class="nav navbar-nav">
                    <li><a class="navbar-brand" href="{% url 'index' %}">
                        <img src="https://flashbox.co/wp-content/uploads/2022/04/Nasrin-karimi.png" alt="Logo" style="width:48px;"></a></li>
                    <li><h2><a class="nav-link" href="{% url 'nasrin:education' %}">Education</a></h2></li>
                    <li><h2><a class="nav-link" href="{% url 'nasrin:experience' %}">Experience</a></h2></li>
                    <li><h2><a class="nav-link" href="{% url 'nasrin:media' %}">Media</a></h2></li>

                </ul>
            
            </div>
        </nav>
        <div class="container">

            {% block body_block %}
            
            
            
            {% endblock %}


        </div>
    </body>
</html>

templates/basic_app/education.html
<!DOCTYPE HTML>
{% extends 'basic_app/base.html' %}
 {% block body_block %}
 <section class="core-rail">
    
    
  

  <div class="details">
    
  
      


<section class="profile">

 <section class="core-section-container core-section-container--with-border pp-section education" data-section="educationsDetails">    
    <h2 class="core-section-container__title">
      
Education

    </h2>


<!---->
<div class="core-section-container__content">

<ul class="education__list">
    





<li class="profile-section-card  education__list-item" data-id="549190271">
<a class="profile-section-card__full-card-link" href="https://ir.linkedin.com/school/cfa-institute-usa/?trk=public_profile_school_profile-section-card_full-click" data-tracking-control-name="public_profile_school_profile-section-card_full-click" data-tracking-will-navigate="">
  <span class="screen-reader-text">
CFA Institute
</span>
</a>

<div class="profile-section-card__contents">
<h3 class="profile-section-card__title">
  
CFA Institute

</h3>

  <h4 class="profile-section-card__subtitle">
      
  <span class="education__item education__item--degree-info">Passed CFA Level 1</span><!----><!---->      
  </h4>



<div class="profile-section-card__meta">
  
<p class="education__item education__item--duration">
  



<span class="date-range">
<time>2018</time> - Present<!---->      </span>

</p>

<!---->      
</div>
</div>


</li>


    





<li class="profile-section-card  education__list-item" data-id="406874297">
<a class="profile-section-card__full-card-link" href="https://ir.linkedin.com/school/khatamuniversity/?trk=public_profile_school_profile-section-card_full-click" data-tracking-control-name="public_profile_school_profile-section-card_full-click" data-tracking-will-navigate="">
  <span class="screen-reader-text">
Khatam University
</span>
</a>
  
<div class="profile-section-card__contents">
<h3 class="profile-section-card__title">
  
Khatam University

</h3>

  <h4 class="profile-section-card__subtitle">
      
  <span class="education__item education__item--degree-info">Master of Science (M.Sc.)</span><span class="education__item education__item--degree-info">Finance, General</span><!---->      
  </h4>



<div class="profile-section-card__meta">
  
<p class="education__item education__item--duration">
  



<span class="date-range">
<time>2013</time> - <time>2016</time><!---->      </span>

</p>

  <div class="education__item--details" data-section="educations">
<!---->              
<div class="show-more-less-text">
<p class="show-more-less-text__text--less">
Thesis :&lrm;<br>        - Measuring Systemic risk in Banking Sector<br>Articles : <br>        - &lrm;Measuring Systemic risk in Banking Sector <br>        - A survey on running CSR in Iran and ranking &lrm;the criteria<br>
</p>

<!---->    </div>

  </div>

</div>
</div>


</li>


    





<li class="profile-section-card  education__list-item" data-id="406871831">
<a class="profile-section-card__full-card-link" href="https://ir.linkedin.com/school/kharazmi-university/?trk=public_profile_school_profile-section-card_full-click" data-tracking-control-name="public_profile_school_profile-section-card_full-click" data-tracking-will-navigate="">
  <span class="screen-reader-text">
Kharazmi University
</span>
</a>
  


<div class="profile-section-card__contents">
<h3 class="profile-section-card__title">
  
Kharazmi University

</h3>

  <h4 class="profile-section-card__subtitle">
      
  <span class="education__item education__item--degree-info">Bachelor of Engineering (B.Eng.)</span><span class="education__item education__item--degree-info">Industrial Engineering</span><!---->      
  </h4>



<div class="profile-section-card__meta">
  
<p class="education__item education__item--duration">
  



<span class="date-range">
<time>2009</time> - <time>2013</time><!---->      </span>

</p>

  <div class="education__item--details" data-section="educations">
<!---->              
<div class="show-more-less-text">
<p class="show-more-less-text__text--less">
Thesis: &lrm;<br>     -  Choosing the best project control system standards &lrm;using AHP approach<br>
</p>

<!---->    </div>

  </div>

</div>
</div>


</li>


    





<li class="profile-section-card  education__list-item" data-id="654827561">
<a class="profile-section-card__full-card-link" href="https://ir.linkedin.com/school/iransampad/?trk=public_profile_school_profile-section-card_full-click" data-tracking-control-name="public_profile_school_profile-section-card_full-click" data-tracking-will-navigate="">
  <span class="screen-reader-text">
National Organization for Development of Exceptional Talents (Sampad)
</span>
</a>
  


<div class="profile-section-card__contents">
<h3 class="profile-section-card__title">
  
National Organization for Development of Exceptional Talents (Sampad)

</h3>

  <h4 class="profile-section-card__subtitle">
      
  <span class="education__item education__item--degree-info">High School Diploma</span><span class="education__item education__item--degree-info">Theoretical and Mathematical Physics</span><!---->      
  </h4>



<div class="profile-section-card__meta">
  
<p class="education__item education__item--duration">
  



<span class="date-range">
<time>2002</time> - <time>2009</time><!---->      </span>

</p>

<!---->      
</div>
</div>


</li>


</ul>

</div>
</section>


 {% endblock %}

templates/basic_app/index.html
{% extends 'basic_app/base.html' %}
 {% block body_block %}
<!---->
<main class="main" id="main-content" role="main">
  <section class="core-rail">
    
    
  

    <div class="details">
      
    
        


  <section class="profile">
     
        <h2 class="core-section-container__title">
          
    About
  
        </h2>
    
  <div class="core-section-container__content">
    
    <p>Experienced Financial Analyst with a demonstrated history of working in the &lrm;information technology, payment, telecommunication, and logistics industries; Skilled in &lrm;forecasting, Preparing business and financial models, Loan structuring,&lrm;&rlm; &rlm;Assessing &lrm;risk, Optimizing portfolio, Financial Reporting &rlm;Analysis with proven efficiency in &lrm;evaluating companies especially startups.&lrm;</p>
  
  </div>
</section>

</body>
{% endblock body_block %}

templates/basic_app/media.html
<!DOCTYPE HTML>
{% extends 'basic_app/base.html' %}
 {% block body_block %}
 <section class="core-rail">
  


   <div class="details">





 <section class="profile">

   <section class="core-section-container core-section-container--with-border pp-section education" data-section="educationsDetails">


      <h1 class="core-section-container__title">

   Social Media

      </h1>

<div class="core-section-container__content">
  <p>Instagram: <a href="https://instagram.com/nasrin_krm?igshid=YmMyMTA2M2Y=">nasrin_krm </a></p>
  <p>Twitter: <a href="https://twitter.com/nasrin_krm?s=21">@nasrin_krm</a></p>
  <p>Telegram: <a href="https://t.me/Nas_Karimi">@Nas_Karimi</a></p>
</div>
</section>


 {% endblock body_block %}